"""Add OAuth tables (clients, authorization codes, tokens)

Revision ID: 52254117488f
Revises: f3378c124740
Create Date: 2026-01-04 00:37:29.059492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52254117488f'
down_revision: Union[str, Sequence[str], None] = 'f3378c124740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_uri', sa.String(length=500), nullable=True),
    sa.Column('redirect_uris', sa.Text(), nullable=False),
    sa.Column('grant_types', sa.Text(), nullable=False),
    sa.Column('response_types', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=500), nullable=False),
    sa.Column('token_endpoint_auth_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_oauth_clients_id'), 'oauth_clients', ['id'], unique=False)
    op.create_table('oauth_authorization_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('scope', sa.String(length=500), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("code_challenge_method IN ('S256', 'plain')", name='valid_code_challenge_method'),
    sa.CheckConstraint("used IN ('true', 'false')", name='valid_used_flag'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_codes_expires_at', 'oauth_authorization_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_client_id'), 'oauth_authorization_codes', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_code'), 'oauth_authorization_codes', ['code'], unique=True)
    op.create_index(op.f('ix_oauth_authorization_codes_expires_at'), 'oauth_authorization_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_id'), 'oauth_authorization_codes', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_user_id'), 'oauth_authorization_codes', ['user_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(length=1000), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=500), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("revoked IN ('true', 'false')", name='valid_revoked_flag'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_access_token'), 'oauth_tokens', ['access_token'], unique=True)
    op.create_index(op.f('ix_oauth_tokens_access_token_expires_at'), 'oauth_tokens', ['access_token_expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_client_id'), 'oauth_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_id'), 'oauth_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_refresh_token'), 'oauth_tokens', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_oauth_tokens_refresh_token_expires_at'), 'oauth_tokens', ['refresh_token_expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    op.create_index('ix_tokens_access_expires', 'oauth_tokens', ['access_token_expires_at'], unique=False)
    op.create_index('ix_tokens_refresh_expires', 'oauth_tokens', ['refresh_token_expires_at'], unique=False)
    op.create_index('ix_audit_created_at', 'task_audit_log', ['created_at'], unique=False)
    op.drop_constraint(op.f('users_oauth_sub_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_oauth_sub'), table_name='users')
    op.create_index(op.f('ix_users_oauth_sub'), 'users', ['oauth_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oauth_sub'), table_name='users')
    op.create_index(op.f('ix_users_oauth_sub'), 'users', ['oauth_sub'], unique=False)
    op.create_unique_constraint(op.f('users_oauth_sub_key'), 'users', ['oauth_sub'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_audit_created_at', table_name='task_audit_log')
    op.drop_index('ix_tokens_refresh_expires', table_name='oauth_tokens')
    op.drop_index('ix_tokens_access_expires', table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_refresh_token_expires_at'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_refresh_token'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_client_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_access_token_expires_at'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_access_token'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_oauth_authorization_codes_user_id'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_id'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_expires_at'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_code'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_client_id'), table_name='oauth_authorization_codes')
    op.drop_index('ix_auth_codes_expires_at', table_name='oauth_authorization_codes')
    op.drop_table('oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_clients_id'), table_name='oauth_clients')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_table('oauth_clients')
    # ### end Alembic commands ###
