"""add_oauth_token_hashes

Revision ID: 5682052542e1
Revises: eb8d46f8d279
Create Date: 2026-01-04 01:55:31.937419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import hashlib


# revision identifiers, used by Alembic.
revision: str = '5682052542e1'
down_revision: Union[str, Sequence[str], None] = 'eb8d46f8d279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('access_token_hash', sa.String(length=64), nullable=True))
    op.add_column('oauth_tokens', sa.Column('refresh_token_hash', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_oauth_tokens_access_token'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_refresh_token'), table_name='oauth_tokens')

    connection = op.get_bind()
    rows = connection.execute(sa.text("SELECT id, access_token, refresh_token FROM oauth_tokens")).fetchall()
    for row in rows:
        access_hash = hashlib.sha256(row.access_token.encode("utf-8")).hexdigest()
        refresh_hash = None
        if row.refresh_token:
            refresh_hash = hashlib.sha256(row.refresh_token.encode("utf-8")).hexdigest()
        connection.execute(
            sa.text(
                "UPDATE oauth_tokens SET access_token_hash = :access_hash, "
                "refresh_token_hash = :refresh_hash WHERE id = :id"
            ),
            {"access_hash": access_hash, "refresh_hash": refresh_hash, "id": row.id},
        )

    op.alter_column('oauth_tokens', 'access_token_hash', nullable=False)
    op.create_index(op.f('ix_oauth_tokens_access_token_hash'), 'oauth_tokens', ['access_token_hash'], unique=True)
    op.create_index(op.f('ix_oauth_tokens_refresh_token_hash'), 'oauth_tokens', ['refresh_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_tokens_refresh_token_hash'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_access_token_hash'), table_name='oauth_tokens')
    op.create_index(op.f('ix_oauth_tokens_refresh_token'), 'oauth_tokens', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_oauth_tokens_access_token'), 'oauth_tokens', ['access_token'], unique=True)
    op.drop_column('oauth_tokens', 'refresh_token_hash')
    op.drop_column('oauth_tokens', 'access_token_hash')
    # ### end Alembic commands ###
